### PR TITLE
Book a venue

### PR DESCRIPTION
**Pull request by jondedman**
I have generated the controller and actions for booking a venue. I'm going to create the view next and then the booking form. I guess all of this should be accessed via he show page?

### CODE REVIEW

**Comment by fransan6** [comment]
Is this on your previous branch or a new one? As the files changed tab shows all the seed changes plus your bookings ones.

LGTM, though I might add `, status: :unprocessable_entity` to the end of line 14 of the Bookings controller

**Comment by jondedman** [comment]
i'm not sure why the seed changes are showing here as well. Probably because all my local files are different until previous pr is merged?

That is a good point about the addition of the error message.

**Comment by fransan6** [comment]
I guess! LGTM once that's error message is inserted

**Comment by alexagodzilla** [comment]
LGTM :)

**Comment by fransan6** [comment]
@jondedman I figured out how to have each pull request not feature your previous pull request's changes - as you did, I created a new branch to work on new edits. But then, I closed all my VS Code and reopened with `code .` I then checked and saw the my previous PR's changes to the seed file weren't present in this one, so it meant I wasn't working on top of what I already had done.

**Comment by jondedman** [comment]
Thanks Fran. I will do that next time

**Pull request merged**
