### PR TITLE
add update and edit to controller, refactor booking form into partial

### PR DESCRIPTION
**Pull request by jondedman**
I have created the edit and update functions in the controller, refactored the form into a partial. The form is rendering on the booking show page. I also updated a button for back to venues and deleted a back to venue button as it seemed unnecessary. The front-end still needs some work.
Screenshot 2023-02-14 at 17 21 06

### CODE REVIEW

**Comment by fransan6** [comment]
I will look at these shortly! Did you git pull origin master this morning btw? I see a few conflicts and we merged a PR last night. 

Is there any way you can merge the master and then submit these edits? Perhaps good to confirm in our call at 6.30!

**Comment by jondedman** [comment]
Hi Fran, sorry i thought i had pulled this morning, but i don't think it worked. I'll do that now.

**Comment by fransan6** [comment]
OK great! Ale mentioned pulling down the master and then merging from your branch. Not sure after that..

**Comment by fransan6** [comment]
LGTM!

**Comment by ilariaperoni** [comment]
LGTM!

**Pull request merged**
