### PR TITLE
update venues index and show pages

### PR DESCRIPTION
**Pull request by fransan6**
Updated the venues index page to have the search bar going across the top to erase some of that empty space.

In addition, I draft updated the show page to include icons, instead of a bullet point list, and to confirm if there are not yet any reviews. I shifted the buttons next to each other and changed the orange button to blue as it seems the orange and green clashed a little.

Happy to rollback any of these changes - just playing around. I don't think this should be merged until everyone has seen it as it's regarding style changes.

### CODE REVIEW

**Comment by fransan6** [comment]
Screenshot 2023-02-12 210549
Screenshot 2023-02-12 211250

**Comment by jondedman** [comment]
nice! how about some of those sweet sweet drop shadows?

**Comment by fransan6** [comment]
Good shout! For now and to remember going forward, I've just popped Cloudinary's own shadow on the show page (it's a little strong but with actual CSS, we can fix it and do it ourselves). For the index, the Bootstrap drop shadows messes the card up a bit so I've left it for now - again, our own CSS and cards should fix that..

**Comment by jondedman** [comment]
Happy to merge, see how it looks and further play around, if needed. @alexagodzilla? @ilariaperoni?

**Comment by fransan6** [comment]
Updated to add `form` tags back into the venues `index.html.erb`

**Comment by fransan6** [comment]
Removing the form tag removes the form functionality so added that back in and form same format as before

**Comment by alexagodzilla** [comment]
LGTM

**Pull request merged**
