### PR TITLE
add user and venue seeding

### PR DESCRIPTION
**Pull request by fransan6**
seed-output

This PR adds seeding for both User and Venue models, to be seeded in that order. As we need to add a user_id to the Venue model, I've included some logic for that. I used two APIs and a standard password for each user that we can all easily remember. I've attached an early screenshot of how this is all displayed (though the the password in the code is now updated to "banana" for easy memory recall).

### CODE REVIEW

**Comment by jondedman** [comment]
I think this looks great, Fran! But isn't the user_id generated by Active record?(or postgresql). I think it is generated automatically once a user is linked to a venue, and saved to the database? I don't think it is something we hard code - i might be wrong!

**Comment by fransan6** [comment]
Thanks! True but we aren't able to save venues without user_id (I tried in the sandbox). For seeding fake users and venues, we might need to hard code it as there won't be real users uploading the venues. Not sure what @ilariaperoni and @alexagodzilla think? I guess later on we'll add a User and upload a Venue to test our authorisation/authentication works.

Also, think we should actually have same number of users and venues so I will update that to 12 each (or can do 16).

**Comment by fransan6** [comment]
Updated this to change numbers of seed generations - Venue from 12 to 15 and User from 8 to 20

**Comment by ilariaperoni** [comment]
LGTM

**Pull request merged**
