### PR TITLE
add validation for unique booking and update booking form

### PR DESCRIPTION
**Pull request by jondedman**
I have added a new gem to validate overlapping dates when a user makes a booking. A custom error message is displayed to the user. I have also added logic to the controller so that the venue name can still be displayed on the booking form even in the case of an error message. I have updated the form with links back to al venues and link back to the show page.

### CODE REVIEW

**Comment by fransan6** [comment]
Great, thank you. This incorporates your previous PR, right?

Also, as the 16.times for Venue generation has been removed, the API limit in the URL will need updating from 15 to 16, as I believe that's where you're getting the number for your new loop.

**Comment by jondedman** [comment]
Thanks Fran. It does, yes. I'll fix the api call limit and push it up again.

**Comment by jondedman** [comment]
Actually, I've just remembered. With the validation now in place, you can't seed for the unavailable venues without commenting out the validation. I'll have a look at this again now.

**Comment by jondedman** [comment]
I have updated the seeding issue. But @fransan6  can you have a look and make sure i haven't altered what you were doing with the seeding of unavailable venues.

**Comment by fransan6** [comment]
Nice!

For line 77, you sample through the first 10 and for line 89, you take the last 5 but don't sample through them. Do we need `.sample` on line 77?
Also line 92 looks to be not needed - instead of renaming `item` as `venue`, the `|item|` on could be renamed `|venue|`, if I've read this correctly.

I can't remember working on what happens with the seeding of unavailable venues so I'll trust that all is good!

**Comment by jondedman** [comment]
I got rid of .sample because it leaves open the possibility that we get a duplicate booking which wont pass validation. Item is just a placeholder variable to avoid confusion.

**Comment by jondedman** [comment]
note: the conflict in the controller. I got rid of the force save because it seems to prevent the displaying of the error message from duplicate bookings. Not sure why!

**Comment by fransan6** [comment]
LGTM!
Thanks for changing the `.save!` and I see what you mean about the bookings, gotcha.

Also, we both thought about editing the bookings new page today. I opened PR #47 so we might have some conflict there later down the line :)

(Just for interest, I've not seen line 29 in the bookings controller before (the local part). What's that for? I've only seen it in instance form when you confirm the placeholder variable 'restaurant', or whatever, is referring to the actual instance variable @ restaurant)

**Comment by jondedman** [comment]
That line 29 is so that we can pass the @venue object back to the view upon rendering. Without that, my little title at the top of the page crashes. I just thought it was good UI to have that there.

**Comment by jondedman** [comment]
I have resolved conflicts. Can this be merged?

**Comment by fransan6** [comment]
Super, I'll merge now!
And thanks for explaining that line

**Pull request merged**
