### PR TITLE
create show page, show action with all the venues information, create…

### PR DESCRIPTION
**Pull request by alexagodzilla**
I've generated a show action for the venue and a show page with all of the venue's information.
Links have been added to allow the user to switch back and forth between the index page and the display page.

### CODE REVIEW

**Comment by fransan6** [comment]
Thanks! LGTM. For the index linking to the show, I was thinking that instead of having the name be a link (as you've done on line 7), we have an actual button that says 'more info' (which is line 9). You think it's better to have no button and link the venue name?
Line 10 has the button formatted mostly correctly but without a working link as I was waiting for the show page to be present before linking - so was just commented out for future use.

**Comment by fransan6** [comment]
It might be useful to show a preview of the index with the name linked and no button?

**Comment by ilariaperoni** [comment]
What if we have no button saying "more info" and we keep the link through the name and the picture later on when we do it?

**Comment by fransan6** [comment]
Absolutely - much better! Would you mind please removing the button?

**Comment by ilariaperoni** [comment]
LGTM, thanks for the comments and removing the button!

**Pull request merged**
